
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:8889/serverdb_tutorial
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true